### ISSUE TITLE
Mod disconnects players when undisguising

### ISSUE THREAD

**Issue by PupsiBubblez** [NucleoidMC/DisguiseLib#4] opened 2021-03-31 17:09 UTC
When ever I do /disguise clear <name> it disconnects the closest (or sometimes all) players on the server

**Comment by samolego** [comment] 2021-03-31 18:16
Do you perhaps use Gunpowder Utilities?

**Comment by PupsiBubblez** [comment] 2021-03-31 18:19
Yea the server is running Gunpowder teleport and utilities

**Comment by samolego** [comment] 2021-03-31 18:57
It's caused by https://github.com/Gunpowder-MC/GunpowderUtilities/issues/17

See also
https://github.com/samolego/Taterzens/issues/4

**Comment by PupsiBubblez** [comment] 2021-03-31 19:12
Ahh ok, Ill keep an eye on this mod then because it can work amazingly well with origins, e.g shapeshifting abilities hopefully gunpowder can fix this

**Comment by samolego** [comment] 2021-04-07 05:23
This should be fixed now :)

**Closed by samolego** 2021-04-07 05:23 UTC

**Comment by PupsiBubblez** [comment] 2021-04-07 17:10
Hey, sorry i just updated the mod to the latest version and tried this again. When doing /disguise _Pupsi clear it still disconnects everyone

**Comment by PupsiBubblez** [comment] 2021-04-07 17:11
[19:07:31] [Netty Epoll Server IO #3/ERROR]: java.lang.UnsupportedOperationException
[19:07:31] [Netty Epoll Server IO #2/ERROR]: java.lang.UnsupportedOperationException
[19:07:31] [Netty Epoll Server IO #0/ERROR]: java.lang.UnsupportedOperationException
[19:07:31] [Netty Epoll Server IO #1/ERROR]: java.lang.UnsupportedOperationException
[19:07:31] [Netty Epoll Server IO #1/ERROR]: java.lang.UnsupportedOperationException
[19:07:31] [Netty Epoll Server IO #0/ERROR]: java.lang.UnsupportedOperationException

This is what the console says

**Comment by samolego** [comment] 2021-04-07 17:15
> Hey, sorry i just updated the mod to the latest version

Did you update Gunpowder utils as well, as the bug lies there ..?

**Comment by PupsiBubblez** [comment] 2021-04-07 23:13
I didn't see that gunpowder had one when I looked, I'll go double check now thanks!

**Comment by samolego** [comment] 2021-04-08 05:42
> I didn't see that gunpowder had one when I looked, I'll go double check now thanks!

Yeah, [1.0.3](https://github.com/Gunpowder-MC/GunpowderUtilities/commit/3f1d98f1b360aea8de25512bf3a889c3f01b8e54) fixes it.
